[build]
builder = "nixpacks"
buildCommand = """
poetry install
poetry run playwright install
poetry run playwright install-deps
"""

[deploy]
startCommand = "poetry run gunicorn wsgi:app"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never"
